tests(e2e): add some heap space for e2e tests
Set node max-old-space-size to 2048 when launching e2e tests to avoid following error
>  FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

This is a quick fix since a global work needs to be done on e2e tests to avoid
- returning such big lists (320 elms)
- running so much tests
- loading so much protractor elements
- etc ...